# Generated by Django 6.0.4 on 2026-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_sale_timestamp_remove_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Electronics', 'Electronics'), ('cosmetics', 'Cosmetics')], default='General', max_length=100),
        ),
    ]
